// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_1d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_address0,
        src_ce0,
        src_q0,
        src_address1,
        src_ce1,
        src_q1,
        src_offset,
        dst_address0,
        dst_ce0,
        dst_we0,
        dst_d0,
        dst_address1,
        dst_ce1,
        dst_we1,
        dst_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] src_address0;
output   src_ce0;
input  [15:0] src_q0;
output  [5:0] src_address1;
output   src_ce1;
input  [15:0] src_q1;
input  [2:0] src_offset;
output  [5:0] dst_address0;
output   dst_ce0;
output   dst_we0;
output  [15:0] dst_d0;
output  [5:0] dst_address1;
output   dst_ce1;
output   dst_we1;
output  [15:0] dst_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg  signed [15:0] reg_210;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] reg_215;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [2:0] src_offset_read_reg_895;
wire   [63:0] zext_ln8_fu_228_p1;
reg   [63:0] zext_ln8_reg_905;
reg   [63:0] zext_ln8_reg_905_pp0_iter1_reg;
wire   [63:0] zext_ln24_fu_241_p1;
reg   [63:0] zext_ln24_reg_915;
reg   [63:0] zext_ln24_reg_915_pp0_iter1_reg;
reg   [63:0] zext_ln24_reg_915_pp0_iter2_reg;
wire   [63:0] zext_ln24_1_fu_253_p1;
reg   [63:0] zext_ln24_1_reg_925;
reg   [63:0] zext_ln24_1_reg_925_pp0_iter1_reg;
reg   [63:0] zext_ln24_1_reg_925_pp0_iter2_reg;
wire   [63:0] zext_ln24_2_fu_265_p1;
reg   [63:0] zext_ln24_2_reg_935;
reg   [63:0] zext_ln24_2_reg_935_pp0_iter1_reg;
reg   [63:0] zext_ln24_2_reg_935_pp0_iter2_reg;
reg  signed [15:0] src_load_reg_945;
wire   [63:0] zext_ln24_3_fu_277_p1;
reg   [63:0] zext_ln24_3_reg_952;
wire   [63:0] zext_ln24_6_fu_289_p1;
reg   [63:0] zext_ln24_6_reg_962;
reg   [63:0] zext_ln24_6_reg_962_pp0_iter1_reg;
reg   [63:0] zext_ln24_6_reg_962_pp0_iter2_reg;
reg  signed [15:0] src_load_3_reg_972;
wire  signed [28:0] sext_ln24_28_fu_294_p1;
reg  signed [28:0] sext_ln24_28_reg_979;
wire   [28:0] mul_ln24_fu_298_p2;
reg  signed [28:0] mul_ln24_reg_984;
wire   [63:0] zext_ln24_4_fu_311_p1;
reg   [63:0] zext_ln24_4_reg_989;
wire    ap_block_pp0_stage3_11001;
reg   [63:0] zext_ln24_4_reg_989_pp0_iter1_reg;
wire   [63:0] zext_ln24_5_fu_323_p1;
reg   [63:0] zext_ln24_5_reg_999;
reg   [63:0] zext_ln24_5_reg_999_pp0_iter1_reg;
reg   [63:0] zext_ln24_5_reg_999_pp0_iter2_reg;
reg   [63:0] zext_ln24_5_reg_999_pp0_iter3_reg;
wire  signed [16:0] sext_ln24_20_fu_328_p1;
reg  signed [16:0] sext_ln24_20_reg_1009;
reg  signed [15:0] src_load_4_reg_1014;
reg  signed [15:0] src_load_7_reg_1020;
wire  signed [28:0] sext_ln24_30_fu_335_p1;
reg  signed [28:0] sext_ln24_30_reg_1027;
wire  signed [28:0] sext_ln24_31_fu_339_p1;
reg  signed [28:0] sext_ln24_31_reg_1033;
wire   [28:0] mul_ln24_16_fu_343_p2;
reg  signed [28:0] mul_ln24_16_reg_1038;
wire  signed [28:0] sext_ln24_33_fu_349_p1;
reg  signed [28:0] sext_ln24_33_reg_1043;
wire   [28:0] mul_ln24_20_fu_352_p2;
reg  signed [28:0] mul_ln24_20_reg_1048;
wire  signed [28:0] sext_ln24_34_fu_358_p1;
wire  signed [16:0] sext_ln24_18_fu_365_p1;
reg  signed [16:0] sext_ln24_18_reg_1059;
wire  signed [16:0] sext_ln24_19_fu_369_p1;
reg  signed [16:0] sext_ln24_19_reg_1065;
wire   [15:0] tmp_fu_397_p2;
reg   [15:0] tmp_reg_1071;
wire   [15:0] tmp235_fu_409_p2;
reg   [15:0] tmp235_reg_1076;
wire   [28:0] tmp_16_fu_440_p2;
reg   [28:0] tmp_16_reg_1081;
wire  signed [28:0] sext_ln24_29_fu_446_p1;
reg  signed [28:0] sext_ln24_29_reg_1087;
wire   [16:0] tmp7_fu_450_p2;
reg  signed [16:0] tmp7_reg_1093;
wire   [17:0] tmp19_fu_471_p2;
reg  signed [17:0] tmp19_reg_1098;
wire  signed [28:0] tmp25_cast17_fu_483_p1;
reg  signed [28:0] tmp25_cast17_reg_1103;
wire  signed [16:0] tmp27_fu_487_p2;
reg  signed [16:0] tmp27_reg_1109;
wire   [15:0] empty_fu_493_p1;
reg   [15:0] empty_reg_1114;
wire  signed [28:0] sext_ln26_fu_503_p1;
reg  signed [28:0] sext_ln26_reg_1119;
wire   [28:0] mul_ln24_24_fu_507_p2;
reg  signed [28:0] mul_ln24_24_reg_1125;
wire  signed [28:0] sext_ln24_27_fu_539_p1;
wire  signed [28:0] tmp7_cast15_fu_542_p1;
reg  signed [28:0] tmp7_cast15_reg_1136;
wire   [28:0] mul_ln26_fu_545_p2;
reg  signed [28:0] mul_ln26_reg_1141;
(* use_dsp48 = "no" *) wire   [17:0] tmp12_fu_559_p2;
reg  signed [17:0] tmp12_reg_1146;
wire  signed [28:0] tmp19_cast_fu_565_p1;
reg  signed [28:0] tmp19_cast_reg_1151;
wire  signed [28:0] sext_ln24_32_fu_568_p1;
reg  signed [28:0] sext_ln24_32_reg_1157;
wire   [28:0] mul_ln24_17_fu_572_p2;
reg  signed [28:0] mul_ln24_17_reg_1162;
reg   [15:0] trunc_ln26_1_reg_1167;
(* use_dsp48 = "no" *) wire   [17:0] tmp40_fu_630_p2;
reg   [17:0] tmp40_reg_1172;
reg  signed [17:0] tmp40_reg_1172_pp0_iter2_reg;
wire  signed [17:0] sext_ln24_24_fu_636_p1;
reg  signed [17:0] sext_ln24_24_reg_1177;
wire  signed [28:0] grp_fu_752_p4;
reg   [28:0] add_ln26_30_reg_1182;
wire   [28:0] grp_fu_744_p3;
reg  signed [28:0] add_ln26_33_reg_1187;
wire  signed [28:0] grp_fu_761_p4;
reg   [28:0] add_ln26_36_reg_1192;
wire   [28:0] tmp33_fu_640_p2;
reg  signed [28:0] tmp33_reg_1197;
wire  signed [28:0] grp_fu_770_p3;
reg   [28:0] add_ln26_41_reg_1202;
wire  signed [28:0] grp_fu_777_p3;
reg   [28:0] add_ln26_47_reg_1207;
wire  signed [28:0] grp_fu_784_p3;
reg  signed [28:0] add_ln26_32_reg_1212;
wire  signed [28:0] grp_fu_798_p3;
reg  signed [28:0] add_ln26_38_reg_1217;
wire   [28:0] grp_fu_791_p3;
reg  signed [28:0] add_ln26_39_reg_1222;
wire   [28:0] grp_fu_805_p3;
reg  signed [28:0] add_ln26_44_reg_1227;
reg   [15:0] trunc_ln26_8_reg_1232;
wire   [28:0] grp_fu_821_p3;
reg   [15:0] trunc_ln26_s_reg_1242;
wire  signed [28:0] grp_fu_837_p3;
reg  signed [28:0] add_ln26_43_reg_1247;
wire   [28:0] mul_ln24_26_fu_683_p2;
reg  signed [28:0] mul_ln24_26_reg_1252;
wire   [28:0] grp_fu_843_p3;
reg  signed [28:0] add_ln26_50_reg_1257;
reg   [15:0] trunc_ln26_9_reg_1262;
reg   [15:0] trunc_ln26_2_reg_1267;
wire   [28:0] grp_fu_867_p3;
reg   [28:0] add_ln26_46_reg_1272;
wire   [28:0] grp_fu_874_p3;
reg  signed [28:0] add_ln26_48_reg_1277;
reg   [15:0] trunc_ln26_4_reg_1282;
reg   [15:0] trunc_ln26_3_reg_1287;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
reg    src_ce1_local;
reg   [5:0] src_address1_local;
reg    src_ce0_local;
reg   [5:0] src_address0_local;
reg    dst_we1_local;
reg   [15:0] dst_d1_local;
reg    dst_ce1_local;
reg   [5:0] dst_address1_local;
reg    dst_we0_local;
reg   [15:0] dst_d0_local;
reg    dst_ce0_local;
reg   [5:0] dst_address0_local;
wire   [5:0] tmp_s_fu_220_p3;
wire   [5:0] tmp_3_fu_233_p3;
wire   [5:0] tmp_4_fu_246_p3;
wire   [5:0] tmp_5_fu_258_p3;
wire   [5:0] tmp_6_fu_270_p3;
wire   [5:0] tmp_10_fu_282_p3;
wire   [14:0] mul_ln24_fu_298_p1;
wire   [5:0] tmp_7_fu_304_p3;
wire   [5:0] tmp_8_fu_316_p3;
wire  signed [15:0] sext_ln11_2_fu_331_p0;
wire  signed [15:0] sext_ln24_30_fu_335_p0;
wire  signed [14:0] mul_ln24_16_fu_343_p1;
wire   [14:0] mul_ln24_20_fu_352_p1;
wire  signed [15:0] sext_ln24_34_fu_358_p0;
wire  signed [15:0] sext_ln24_22_fu_376_p0;
wire  signed [15:0] sext_ln24_23_fu_380_p0;
wire  signed [15:0] tmp1_fu_403_p0;
wire  signed [15:0] tmp1_fu_403_p1;
wire   [15:0] tmp1_fu_403_p2;
wire   [15:0] tmp5733_fu_422_p2;
wire   [28:0] tmp_9_fu_415_p3;
wire   [28:0] shl_ln_fu_390_p3;
wire   [28:0] add_ln24_fu_434_p2;
wire   [28:0] tmp15_fu_426_p3;
wire  signed [15:0] sext_ln24_29_fu_446_p0;
wire  signed [16:0] sext_ln24_22_fu_376_p1;
wire  signed [16:0] sext_ln24_fu_362_p1;
wire   [16:0] tmp17_fu_456_p2;
wire  signed [17:0] tmp17_cast_fu_461_p1;
wire  signed [17:0] sext_ln11_fu_373_p1;
wire   [17:0] tmp18_fu_465_p2;
wire  signed [17:0] sext_ln24_26_fu_387_p1;
wire  signed [16:0] sext_ln24_23_fu_380_p1;
wire  signed [16:0] tmp25_fu_477_p2;
wire  signed [16:0] sext_ln24_25_fu_384_p1;
wire  signed [16:0] tmp35_fu_497_p2;
wire  signed [15:0] mul_ln24_24_fu_507_p0;
wire  signed [14:0] mul_ln24_24_fu_507_p1;
wire   [28:0] tmp3_fu_516_p3;
wire   [28:0] add_ln26_fu_523_p2;
wire   [13:0] mul_ln26_fu_545_p1;
wire   [16:0] tmp11_fu_551_p2;
wire  signed [17:0] tmp11_cast_fu_555_p1;
wire  signed [17:0] sext_ln24_21_fu_512_p1;
wire   [14:0] mul_ln24_17_fu_572_p1;
wire  signed [28:0] tmp27_cast_fu_578_p1;
wire   [28:0] p_shl2_fu_581_p3;
wire   [28:0] p_shl_fu_594_p3;
wire   [28:0] sub_ln26_fu_601_p2;
wire   [28:0] tmp28_fu_588_p2;
wire   [28:0] add_ln26_11_fu_606_p2;
wire   [16:0] tmp39_fu_622_p2;
wire  signed [17:0] tmp39_cast_fu_626_p1;
wire  signed [16:0] tmp33_fu_640_p0;
wire   [12:0] tmp33_fu_640_p1;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_34_fu_645_p2;
wire  signed [28:0] add_ln26_8_fu_649_p1;
wire   [28:0] grp_fu_813_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_8_fu_649_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_40_fu_664_p2;
wire  signed [28:0] add_ln26_10_fu_668_p1;
wire   [28:0] grp_fu_829_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_10_fu_668_p2;
wire  signed [15:0] mul_ln24_26_fu_683_p0;
wire  signed [14:0] mul_ln24_26_fu_683_p1;
wire  signed [28:0] trunc_ln26_9_fu_688_p1;
wire   [28:0] grp_fu_850_p4;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_45_fu_697_p2;
wire  signed [28:0] add_ln26_12_fu_701_p1;
wire   [28:0] grp_fu_860_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_12_fu_701_p2;
wire  signed [28:0] grp_fu_880_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_51_fu_716_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_14_fu_720_p2;
wire  signed [28:0] trunc_ln26_3_fu_735_p1;
wire   [28:0] grp_fu_887_p4;
wire  signed [14:0] grp_fu_744_p1;
wire   [12:0] grp_fu_744_p2;
wire  signed [15:0] grp_fu_752_p0;
wire  signed [15:0] grp_fu_752_p1;
wire  signed [16:0] sext_ln11_2_fu_331_p1;
wire   [11:0] grp_fu_752_p2;
wire  signed [15:0] grp_fu_761_p0;
wire  signed [15:0] grp_fu_761_p1;
wire   [12:0] grp_fu_761_p2;
wire  signed [15:0] grp_fu_770_p0;
wire  signed [14:0] grp_fu_770_p1;
wire  signed [15:0] grp_fu_777_p0;
wire   [13:0] grp_fu_777_p1;
wire  signed [14:0] grp_fu_784_p1;
wire  signed [15:0] grp_fu_791_p0;
wire  signed [14:0] grp_fu_791_p1;
wire   [12:0] grp_fu_791_p2;
wire   [11:0] grp_fu_798_p1;
wire   [12:0] grp_fu_805_p1;
wire   [12:0] grp_fu_805_p2;
wire  signed [15:0] grp_fu_813_p0;
wire   [13:0] grp_fu_813_p1;
wire   [13:0] grp_fu_821_p1;
wire   [12:0] grp_fu_821_p2;
wire  signed [15:0] grp_fu_829_p0;
wire   [13:0] grp_fu_829_p1;
wire  signed [15:0] grp_fu_837_p0;
wire   [13:0] grp_fu_837_p1;
wire  signed [16:0] grp_fu_843_p0;
wire   [11:0] grp_fu_843_p1;
wire   [12:0] grp_fu_843_p2;
wire   [12:0] grp_fu_850_p2;
wire  signed [15:0] grp_fu_860_p0;
wire  signed [14:0] grp_fu_860_p1;
wire  signed [17:0] grp_fu_867_p0;
wire   [12:0] grp_fu_867_p1;
wire   [12:0] grp_fu_867_p2;
wire  signed [15:0] grp_fu_874_p0;
wire   [13:0] grp_fu_874_p1;
wire  signed [16:0] grp_fu_880_p0;
wire   [12:0] grp_fu_880_p1;
wire  signed [15:0] grp_fu_887_p1;
wire   [13:0] grp_fu_887_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_0to3;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to4;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U76(
    .din0(reg_210),
    .din1(mul_ln24_fu_298_p1),
    .dout(mul_ln24_fu_298_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U77(
    .din0(reg_215),
    .din1(mul_ln24_16_fu_343_p1),
    .dout(mul_ln24_16_fu_343_p2)
);

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U78(
    .din0(src_load_3_reg_972),
    .din1(mul_ln24_20_fu_352_p1),
    .dout(mul_ln24_20_fu_352_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U79(
    .din0(mul_ln24_24_fu_507_p0),
    .din1(mul_ln24_24_fu_507_p1),
    .dout(mul_ln24_24_fu_507_p2)
);

dct_mul_17s_14ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 29 ))
mul_17s_14ns_29_1_1_U80(
    .din0(tmp7_reg_1093),
    .din1(mul_ln26_fu_545_p1),
    .dout(mul_ln26_fu_545_p2)
);

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U81(
    .din0(reg_210),
    .din1(mul_ln24_17_fu_572_p1),
    .dout(mul_ln24_17_fu_572_p2)
);

dct_mul_17s_13ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mul_17s_13ns_29_1_1_U82(
    .din0(tmp33_fu_640_p0),
    .din1(tmp33_fu_640_p1),
    .dout(tmp33_fu_640_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U83(
    .din0(mul_ln24_26_fu_683_p0),
    .din1(mul_ln24_26_fu_683_p1),
    .dout(mul_ln24_26_fu_683_p2)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U84(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln24_30_fu_335_p0),
    .din1(grp_fu_744_p1),
    .din2(grp_fu_744_p2),
    .ce(1'b1),
    .dout(grp_fu_744_p3)
);

dct_ama_submuladd_16s_16s_12ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_12ns_29s_29_4_1_U85(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_752_p0),
    .din1(grp_fu_752_p1),
    .din2(grp_fu_752_p2),
    .din3(mul_ln24_reg_984),
    .ce(1'b1),
    .dout(grp_fu_752_p4)
);

dct_ama_submuladd_16s_16s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_13ns_29s_29_4_1_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_761_p0),
    .din1(grp_fu_761_p1),
    .din2(grp_fu_761_p2),
    .din3(mul_ln24_16_reg_1038),
    .ce(1'b1),
    .dout(grp_fu_761_p4)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_770_p0),
    .din1(grp_fu_770_p1),
    .din2(mul_ln24_20_reg_1048),
    .ce(1'b1),
    .dout(grp_fu_770_p3)
);

dct_mac_muladd_16s_14ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_1_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_777_p0),
    .din1(grp_fu_777_p1),
    .din2(mul_ln24_24_reg_1125),
    .ce(1'b1),
    .dout(grp_fu_777_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln24_29_fu_446_p0),
    .din1(grp_fu_784_p1),
    .din2(mul_ln26_reg_1141),
    .ce(1'b1),
    .dout(grp_fu_784_p3)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_791_p0),
    .din1(grp_fu_791_p1),
    .din2(grp_fu_791_p2),
    .ce(1'b1),
    .dout(grp_fu_791_p3)
);

dct_mac_muladd_17s_12ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_29s_29_4_1_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp25_fu_477_p2),
    .din1(grp_fu_798_p1),
    .din2(mul_ln24_17_reg_1162),
    .ce(1'b1),
    .dout(grp_fu_798_p3)
);

dct_mac_muladd_17s_13ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_13ns_29_4_1_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp35_fu_497_p2),
    .din1(grp_fu_805_p1),
    .din2(grp_fu_805_p2),
    .ce(1'b1),
    .dout(grp_fu_805_p3)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_813_p0),
    .din1(grp_fu_813_p1),
    .din2(add_ln26_30_reg_1182),
    .ce(1'b1),
    .dout(grp_fu_813_p3)
);

dct_mac_muladd_18s_14ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_14ns_13ns_29_4_1_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp19_reg_1098),
    .din1(grp_fu_821_p1),
    .din2(grp_fu_821_p2),
    .ce(1'b1),
    .dout(grp_fu_821_p3)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U95(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_829_p0),
    .din1(grp_fu_829_p1),
    .din2(add_ln26_36_reg_1192),
    .ce(1'b1),
    .dout(grp_fu_829_p3)
);

dct_mac_muladd_16s_14ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_1_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_837_p0),
    .din1(grp_fu_837_p1),
    .din2(tmp33_reg_1197),
    .ce(1'b1),
    .dout(grp_fu_837_p3)
);

dct_mac_muladd_17s_12ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_1_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_843_p0),
    .din1(grp_fu_843_p1),
    .din2(grp_fu_843_p2),
    .ce(1'b1),
    .dout(grp_fu_843_p3)
);

dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_18s_16s_13ns_29ns_29_4_1_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp12_reg_1146),
    .din1(reg_215),
    .din2(grp_fu_850_p2),
    .din3(grp_fu_821_p3),
    .ce(1'b1),
    .dout(grp_fu_850_p4)
);

dct_mac_muladd_16s_15s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29ns_29_4_1_U99(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_860_p0),
    .din1(grp_fu_860_p1),
    .din2(add_ln26_41_reg_1202),
    .ce(1'b1),
    .dout(grp_fu_860_p3)
);

dct_mac_muladd_18s_13ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_13ns_13ns_29_4_1_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_867_p0),
    .din1(grp_fu_867_p1),
    .din2(grp_fu_867_p2),
    .ce(1'b1),
    .dout(grp_fu_867_p3)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U101(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_874_p0),
    .din1(grp_fu_874_p1),
    .din2(add_ln26_47_reg_1207),
    .ce(1'b1),
    .dout(grp_fu_874_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_1_U102(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_880_p0),
    .din1(grp_fu_880_p1),
    .din2(mul_ln24_26_reg_1252),
    .ce(1'b1),
    .dout(grp_fu_880_p3)
);

dct_ama_submuladd_18s_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_18s_16s_14ns_29ns_29_4_1_U103(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp40_reg_1172_pp0_iter2_reg),
    .din1(grp_fu_887_p1),
    .din2(grp_fu_887_p2),
    .din3(add_ln26_46_reg_1272),
    .ce(1'b1),
    .dout(grp_fu_887_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_210 <= src_q1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_210 <= src_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_215 <= src_q0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_215 <= src_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln26_30_reg_1182 <= grp_fu_752_p4;
        add_ln26_33_reg_1187 <= grp_fu_744_p3;
        add_ln26_36_reg_1192 <= grp_fu_761_p4;
        add_ln26_41_reg_1202 <= grp_fu_770_p3;
        add_ln26_47_reg_1207 <= grp_fu_777_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln26_32_reg_1212 <= grp_fu_784_p3;
        add_ln26_38_reg_1217 <= grp_fu_798_p3;
        add_ln26_39_reg_1222 <= grp_fu_791_p3;
        add_ln26_44_reg_1227 <= grp_fu_805_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln26_43_reg_1247 <= grp_fu_837_p3;
        add_ln26_50_reg_1257 <= grp_fu_843_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln26_46_reg_1272 <= grp_fu_867_p3;
        add_ln26_48_reg_1277 <= grp_fu_874_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_reg_1114 <= empty_fu_493_p1;
        mul_ln24_24_reg_1125 <= mul_ln24_24_fu_507_p2;
        mul_ln24_26_reg_1252 <= mul_ln24_26_fu_683_p2;
        sext_ln24_18_reg_1059 <= sext_ln24_18_fu_365_p1;
        sext_ln24_19_reg_1065 <= sext_ln24_19_fu_369_p1;
        sext_ln24_29_reg_1087 <= sext_ln24_29_fu_446_p1;
        sext_ln26_reg_1119 <= sext_ln26_fu_503_p1;
        src_offset_read_reg_895 <= src_offset;
        tmp19_reg_1098 <= tmp19_fu_471_p2;
        tmp235_reg_1076 <= tmp235_fu_409_p2;
        tmp25_cast17_reg_1103 <= tmp25_cast17_fu_483_p1;
        tmp27_reg_1109 <= tmp27_fu_487_p2;
        tmp7_reg_1093 <= tmp7_fu_450_p2;
        tmp_16_reg_1081[28 : 13] <= tmp_16_fu_440_p2[28 : 13];
        tmp_reg_1071 <= tmp_fu_397_p2;
        trunc_ln26_8_reg_1232 <= {{add_ln26_8_fu_649_p2[28:13]}};
        trunc_ln26_s_reg_1242 <= {{add_ln26_10_fu_668_p2[28:13]}};
        zext_ln24_reg_915[5 : 3] <= zext_ln24_fu_241_p1[5 : 3];
        zext_ln24_reg_915_pp0_iter1_reg[5 : 3] <= zext_ln24_reg_915[5 : 3];
        zext_ln24_reg_915_pp0_iter2_reg[5 : 3] <= zext_ln24_reg_915_pp0_iter1_reg[5 : 3];
        zext_ln8_reg_905[5 : 3] <= zext_ln8_fu_228_p1[5 : 3];
        zext_ln8_reg_905_pp0_iter1_reg[5 : 3] <= zext_ln8_reg_905[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_ln24_16_reg_1038 <= mul_ln24_16_fu_343_p2;
        mul_ln24_20_reg_1048 <= mul_ln24_20_fu_352_p2;
        sext_ln24_20_reg_1009 <= sext_ln24_20_fu_328_p1;
        sext_ln24_30_reg_1027 <= sext_ln24_30_fu_335_p1;
        sext_ln24_31_reg_1033 <= sext_ln24_31_fu_339_p1;
        sext_ln24_33_reg_1043 <= sext_ln24_33_fu_349_p1;
        trunc_ln26_4_reg_1282 <= {{add_ln26_14_fu_720_p2[28:13]}};
        zext_ln24_4_reg_989[5 : 3] <= zext_ln24_4_fu_311_p1[5 : 3];
        zext_ln24_4_reg_989_pp0_iter1_reg[5 : 3] <= zext_ln24_4_reg_989[5 : 3];
        zext_ln24_5_reg_999[5 : 3] <= zext_ln24_5_fu_323_p1[5 : 3];
        zext_ln24_5_reg_999_pp0_iter1_reg[5 : 3] <= zext_ln24_5_reg_999[5 : 3];
        zext_ln24_5_reg_999_pp0_iter2_reg[5 : 3] <= zext_ln24_5_reg_999_pp0_iter1_reg[5 : 3];
        zext_ln24_5_reg_999_pp0_iter3_reg[5 : 3] <= zext_ln24_5_reg_999_pp0_iter2_reg[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln24_17_reg_1162 <= mul_ln24_17_fu_572_p2;
        mul_ln26_reg_1141 <= mul_ln26_fu_545_p2;
        sext_ln24_32_reg_1157 <= sext_ln24_32_fu_568_p1;
        tmp12_reg_1146 <= tmp12_fu_559_p2;
        tmp19_cast_reg_1151 <= tmp19_cast_fu_565_p1;
        tmp40_reg_1172 <= tmp40_fu_630_p2;
        tmp40_reg_1172_pp0_iter2_reg <= tmp40_reg_1172;
        tmp7_cast15_reg_1136 <= tmp7_cast15_fu_542_p1;
        trunc_ln26_1_reg_1167 <= {{add_ln26_11_fu_606_p2[28:13]}};
        trunc_ln26_2_reg_1267 <= {{add_ln26_12_fu_701_p2[28:13]}};
        trunc_ln26_3_reg_1287 <= {{trunc_ln26_3_fu_735_p1[28:13]}};
        trunc_ln26_9_reg_1262 <= {{trunc_ln26_9_fu_688_p1[28:13]}};
        zext_ln24_1_reg_925[5 : 3] <= zext_ln24_1_fu_253_p1[5 : 3];
        zext_ln24_1_reg_925_pp0_iter1_reg[5 : 3] <= zext_ln24_1_reg_925[5 : 3];
        zext_ln24_1_reg_925_pp0_iter2_reg[5 : 3] <= zext_ln24_1_reg_925_pp0_iter1_reg[5 : 3];
        zext_ln24_2_reg_935[5 : 3] <= zext_ln24_2_fu_265_p1[5 : 3];
        zext_ln24_2_reg_935_pp0_iter1_reg[5 : 3] <= zext_ln24_2_reg_935[5 : 3];
        zext_ln24_2_reg_935_pp0_iter2_reg[5 : 3] <= zext_ln24_2_reg_935_pp0_iter1_reg[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln24_reg_984 <= mul_ln24_fu_298_p2;
        sext_ln24_24_reg_1177 <= sext_ln24_24_fu_636_p1;
        sext_ln24_28_reg_979 <= sext_ln24_28_fu_294_p1;
        tmp33_reg_1197 <= tmp33_fu_640_p2;
        zext_ln24_3_reg_952[5 : 3] <= zext_ln24_3_fu_277_p1[5 : 3];
        zext_ln24_6_reg_962[5 : 3] <= zext_ln24_6_fu_289_p1[5 : 3];
        zext_ln24_6_reg_962_pp0_iter1_reg[5 : 3] <= zext_ln24_6_reg_962[5 : 3];
        zext_ln24_6_reg_962_pp0_iter2_reg[5 : 3] <= zext_ln24_6_reg_962_pp0_iter1_reg[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        src_load_3_reg_972 <= src_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        src_load_4_reg_1014 <= src_q1;
        src_load_7_reg_1020 <= src_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        src_load_reg_945 <= src_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_address0_local = zext_ln24_5_reg_999_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_address0_local = zext_ln24_4_reg_989_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_address0_local = zext_ln24_1_reg_925_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_address0_local = zext_ln24_reg_915_pp0_iter2_reg;
    end else begin
        dst_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_address1_local = zext_ln24_6_reg_962_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_address1_local = zext_ln24_2_reg_935_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_address1_local = zext_ln24_3_reg_952;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_address1_local = zext_ln8_reg_905_pp0_iter1_reg;
    end else begin
        dst_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        dst_ce0_local = 1'b1;
    end else begin
        dst_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        dst_ce1_local = 1'b1;
    end else begin
        dst_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_d0_local = trunc_ln26_3_reg_1287;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_d0_local = trunc_ln26_2_reg_1267;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_d0_local = trunc_ln26_9_reg_1262;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_d0_local = trunc_ln26_8_reg_1232;
    end else begin
        dst_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_d1_local = trunc_ln26_4_reg_1282;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_d1_local = trunc_ln26_s_reg_1242;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_d1_local = trunc_ln26_1_reg_1167;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_d1_local = {{add_ln26_fu_523_p2[28:13]}};
    end else begin
        dst_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        dst_we0_local = 1'b1;
    end else begin
        dst_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        dst_we1_local = 1'b1;
    end else begin
        dst_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        src_address0_local = zext_ln24_5_fu_323_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        src_address0_local = zext_ln24_6_fu_289_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        src_address0_local = zext_ln24_2_fu_265_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_address0_local = zext_ln24_fu_241_p1;
    end else begin
        src_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        src_address1_local = zext_ln24_4_fu_311_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        src_address1_local = zext_ln24_3_fu_277_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        src_address1_local = zext_ln24_1_fu_253_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_address1_local = zext_ln8_fu_228_p1;
    end else begin
        src_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        src_ce0_local = 1'b1;
    end else begin
        src_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        src_ce1_local = 1'b1;
    end else begin
        src_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_434_p2 = (tmp_9_fu_415_p3 + shl_ln_fu_390_p3);

assign add_ln26_10_fu_668_p1 = grp_fu_829_p3;

assign add_ln26_10_fu_668_p2 = ($signed(add_ln26_40_fu_664_p2) + $signed(add_ln26_10_fu_668_p1));

assign add_ln26_11_fu_606_p2 = (sub_ln26_fu_601_p2 + tmp28_fu_588_p2);

assign add_ln26_12_fu_701_p1 = grp_fu_860_p3;

assign add_ln26_12_fu_701_p2 = ($signed(add_ln26_45_fu_697_p2) + $signed(add_ln26_12_fu_701_p1));

assign add_ln26_14_fu_720_p2 = ($signed(add_ln26_51_fu_716_p2) + $signed(add_ln26_48_reg_1277));

assign add_ln26_34_fu_645_p2 = ($signed(add_ln26_33_reg_1187) + $signed(add_ln26_32_reg_1212));

assign add_ln26_40_fu_664_p2 = ($signed(add_ln26_39_reg_1222) + $signed(add_ln26_38_reg_1217));

assign add_ln26_45_fu_697_p2 = ($signed(add_ln26_44_reg_1227) + $signed(add_ln26_43_reg_1247));

assign add_ln26_51_fu_716_p2 = ($signed(add_ln26_50_reg_1257) + $signed(grp_fu_880_p3));

assign add_ln26_8_fu_649_p1 = grp_fu_813_p3;

assign add_ln26_8_fu_649_p2 = ($signed(add_ln26_34_fu_645_p2) + $signed(add_ln26_8_fu_649_p1));

assign add_ln26_fu_523_p2 = (tmp_16_reg_1081 + tmp3_fu_516_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign dst_address0 = dst_address0_local;

assign dst_address1 = dst_address1_local;

assign dst_ce0 = dst_ce0_local;

assign dst_ce1 = dst_ce1_local;

assign dst_d0 = dst_d0_local;

assign dst_d1 = dst_d1_local;

assign dst_we0 = dst_we0_local;

assign dst_we1 = dst_we1_local;

assign empty_fu_493_p1 = tmp27_fu_487_p2[15:0];

assign grp_fu_744_p1 = 29'd536859550;

assign grp_fu_744_p2 = 29'd4096;

assign grp_fu_752_p0 = sext_ln24_20_fu_328_p1;

assign grp_fu_752_p1 = sext_ln11_2_fu_331_p1;

assign grp_fu_752_p2 = 29'd2260;

assign grp_fu_761_p0 = sext_ln11_2_fu_331_p1;

assign grp_fu_761_p1 = sext_ln24_20_fu_328_p1;

assign grp_fu_761_p2 = 29'd6436;

assign grp_fu_770_p0 = sext_ln24_34_fu_358_p1;

assign grp_fu_770_p1 = 29'd536861280;

assign grp_fu_777_p0 = sext_ln24_34_fu_358_p1;

assign grp_fu_777_p1 = 29'd11363;

assign grp_fu_784_p1 = 29'd536861280;

assign grp_fu_791_p0 = sext_ln24_30_reg_1027;

assign grp_fu_791_p1 = 29'd536861280;

assign grp_fu_791_p2 = 29'd4096;

assign grp_fu_798_p1 = 29'd2260;

assign grp_fu_805_p1 = 29'd6436;

assign grp_fu_805_p2 = 29'd4096;

assign grp_fu_813_p0 = sext_ln24_27_fu_539_p1;

assign grp_fu_813_p1 = 29'd11363;

assign grp_fu_821_p1 = 29'd10703;

assign grp_fu_821_p2 = 29'd4096;

assign grp_fu_829_p0 = sext_ln24_27_fu_539_p1;

assign grp_fu_829_p1 = 29'd9633;

assign grp_fu_837_p0 = sext_ln24_29_reg_1087;

assign grp_fu_837_p1 = 29'd11363;

assign grp_fu_843_p0 = sext_ln26_reg_1119;

assign grp_fu_843_p1 = 29'd2260;

assign grp_fu_843_p2 = 29'd4096;

assign grp_fu_850_p2 = 29'd4433;

assign grp_fu_860_p0 = sext_ln24_28_reg_979;

assign grp_fu_860_p1 = 29'd536859550;

assign grp_fu_867_p0 = tmp19_cast_reg_1151;

assign grp_fu_867_p1 = 29'd4433;

assign grp_fu_867_p2 = 29'd4096;

assign grp_fu_874_p0 = sext_ln24_31_reg_1033;

assign grp_fu_874_p1 = 29'd9633;

assign grp_fu_880_p0 = tmp25_cast17_reg_1103;

assign grp_fu_880_p1 = 29'd6436;

assign grp_fu_887_p1 = sext_ln24_24_reg_1177;

assign grp_fu_887_p2 = 29'd10703;

assign mul_ln24_16_fu_343_p1 = 29'd536859550;

assign mul_ln24_17_fu_572_p1 = 29'd11363;

assign mul_ln24_20_fu_352_p1 = 29'd9633;

assign mul_ln24_24_fu_507_p0 = sext_ln24_33_reg_1043;

assign mul_ln24_24_fu_507_p1 = 29'd536859550;

assign mul_ln24_26_fu_683_p0 = sext_ln24_32_reg_1157;

assign mul_ln24_26_fu_683_p1 = 29'd536861280;

assign mul_ln24_fu_298_p1 = 29'd9633;

assign mul_ln26_fu_545_p1 = 29'd6436;

assign p_shl2_fu_581_p3 = {{empty_reg_1114}, {13'd0}};

assign p_shl_fu_594_p3 = {{tmp_reg_1071}, {13'd0}};

assign sext_ln11_2_fu_331_p0 = src_q1;

assign sext_ln11_2_fu_331_p1 = sext_ln11_2_fu_331_p0;

assign sext_ln11_fu_373_p1 = src_load_4_reg_1014;

assign sext_ln24_18_fu_365_p1 = reg_210;

assign sext_ln24_19_fu_369_p1 = reg_215;

assign sext_ln24_20_fu_328_p1 = src_load_3_reg_972;

assign sext_ln24_21_fu_512_p1 = reg_210;

assign sext_ln24_22_fu_376_p0 = src_q1;

assign sext_ln24_22_fu_376_p1 = sext_ln24_22_fu_376_p0;

assign sext_ln24_23_fu_380_p0 = src_q0;

assign sext_ln24_23_fu_380_p1 = sext_ln24_23_fu_380_p0;

assign sext_ln24_24_fu_636_p1 = reg_215;

assign sext_ln24_25_fu_384_p1 = src_load_7_reg_1020;

assign sext_ln24_26_fu_387_p1 = src_load_7_reg_1020;

assign sext_ln24_27_fu_539_p1 = src_load_reg_945;

assign sext_ln24_28_fu_294_p1 = reg_210;

assign sext_ln24_29_fu_446_p0 = src_q0;

assign sext_ln24_29_fu_446_p1 = sext_ln24_29_fu_446_p0;

assign sext_ln24_30_fu_335_p0 = src_q0;

assign sext_ln24_30_fu_335_p1 = sext_ln24_30_fu_335_p0;

assign sext_ln24_31_fu_339_p1 = reg_215;

assign sext_ln24_32_fu_568_p1 = reg_210;

assign sext_ln24_33_fu_349_p1 = src_load_3_reg_972;

assign sext_ln24_34_fu_358_p0 = src_q1;

assign sext_ln24_34_fu_358_p1 = sext_ln24_34_fu_358_p0;

assign sext_ln24_fu_362_p1 = src_load_reg_945;

assign sext_ln26_fu_503_p1 = tmp35_fu_497_p2;

assign shl_ln_fu_390_p3 = {{src_load_7_reg_1020}, {13'd0}};

assign src_address0 = src_address0_local;

assign src_address1 = src_address1_local;

assign src_ce0 = src_ce0_local;

assign src_ce1 = src_ce1_local;

assign sub_ln26_fu_601_p2 = (tmp_16_reg_1081 - p_shl_fu_594_p3);

assign tmp11_cast_fu_555_p1 = $signed(tmp11_fu_551_p2);

assign tmp11_fu_551_p2 = ($signed(sext_ln24_18_reg_1059) - $signed(sext_ln24_19_reg_1065));

assign tmp12_fu_559_p2 = ($signed(tmp11_cast_fu_555_p1) - $signed(sext_ln24_21_fu_512_p1));

assign tmp15_fu_426_p3 = {{tmp5733_fu_422_p2}, {13'd0}};

assign tmp17_cast_fu_461_p1 = $signed(tmp17_fu_456_p2);

assign tmp17_fu_456_p2 = ($signed(sext_ln24_fu_362_p1) - $signed(sext_ln24_20_reg_1009));

assign tmp18_fu_465_p2 = ($signed(tmp17_cast_fu_461_p1) - $signed(sext_ln11_fu_373_p1));

assign tmp19_cast_fu_565_p1 = tmp19_reg_1098;

assign tmp19_fu_471_p2 = ($signed(tmp18_fu_465_p2) + $signed(sext_ln24_26_fu_387_p1));

assign tmp1_fu_403_p0 = src_q1;

assign tmp1_fu_403_p1 = src_q0;

assign tmp1_fu_403_p2 = ($signed(tmp1_fu_403_p0) + $signed(tmp1_fu_403_p1));

assign tmp235_fu_409_p2 = (tmp1_fu_403_p2 + tmp_fu_397_p2);

assign tmp25_cast17_fu_483_p1 = tmp25_fu_477_p2;

assign tmp25_fu_477_p2 = ($signed(sext_ln24_23_fu_380_p1) - $signed(sext_ln24_18_fu_365_p1));

assign tmp27_cast_fu_578_p1 = tmp27_reg_1109;

assign tmp27_fu_487_p2 = ($signed(sext_ln24_23_fu_380_p1) + $signed(sext_ln24_22_fu_376_p1));

assign tmp28_fu_588_p2 = ($signed(tmp27_cast_fu_578_p1) - $signed(p_shl2_fu_581_p3));

assign tmp33_fu_640_p0 = tmp7_cast15_reg_1136;

assign tmp33_fu_640_p1 = 29'd2260;

assign tmp35_fu_497_p2 = ($signed(sext_ln24_fu_362_p1) - $signed(sext_ln24_25_fu_384_p1));

assign tmp39_cast_fu_626_p1 = $signed(tmp39_fu_622_p2);

assign tmp39_fu_622_p2 = ($signed(sext_ln24_19_reg_1065) - $signed(sext_ln24_18_reg_1059));

assign tmp3_fu_516_p3 = {{tmp235_reg_1076}, {13'd0}};

assign tmp40_fu_630_p2 = ($signed(tmp39_cast_fu_626_p1) + $signed(sext_ln24_21_fu_512_p1));

assign tmp5733_fu_422_p2 = ($signed(src_load_4_reg_1014) + $signed(src_load_3_reg_972));

assign tmp7_cast15_fu_542_p1 = tmp7_reg_1093;

assign tmp7_fu_450_p2 = ($signed(sext_ln24_19_fu_369_p1) - $signed(sext_ln24_22_fu_376_p1));

assign tmp_10_fu_282_p3 = {{src_offset_read_reg_895}, {3'd7}};

assign tmp_16_fu_440_p2 = (add_ln24_fu_434_p2 + tmp15_fu_426_p3);

assign tmp_3_fu_233_p3 = {{src_offset}, {3'd1}};

assign tmp_4_fu_246_p3 = {{src_offset_read_reg_895}, {3'd2}};

assign tmp_5_fu_258_p3 = {{src_offset_read_reg_895}, {3'd3}};

assign tmp_6_fu_270_p3 = {{src_offset_read_reg_895}, {3'd4}};

assign tmp_7_fu_304_p3 = {{src_offset_read_reg_895}, {3'd5}};

assign tmp_8_fu_316_p3 = {{src_offset_read_reg_895}, {3'd6}};

assign tmp_9_fu_415_p3 = {{src_load_reg_945}, {13'd4096}};

assign tmp_fu_397_p2 = ($signed(reg_215) + $signed(reg_210));

assign tmp_s_fu_220_p3 = {{src_offset}, {3'd0}};

assign trunc_ln26_3_fu_735_p1 = grp_fu_887_p4;

assign trunc_ln26_9_fu_688_p1 = grp_fu_850_p4;

assign zext_ln24_1_fu_253_p1 = tmp_4_fu_246_p3;

assign zext_ln24_2_fu_265_p1 = tmp_5_fu_258_p3;

assign zext_ln24_3_fu_277_p1 = tmp_6_fu_270_p3;

assign zext_ln24_4_fu_311_p1 = tmp_7_fu_304_p3;

assign zext_ln24_5_fu_323_p1 = tmp_8_fu_316_p3;

assign zext_ln24_6_fu_289_p1 = tmp_10_fu_282_p3;

assign zext_ln24_fu_241_p1 = tmp_3_fu_233_p3;

assign zext_ln8_fu_228_p1 = tmp_s_fu_220_p3;

always @ (posedge ap_clk) begin
    zext_ln8_reg_905[2:0] <= 3'b000;
    zext_ln8_reg_905[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_905_pp0_iter1_reg[2:0] <= 3'b000;
    zext_ln8_reg_905_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_reg_915[2:0] <= 3'b001;
    zext_ln24_reg_915[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_reg_915_pp0_iter1_reg[2:0] <= 3'b001;
    zext_ln24_reg_915_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_reg_915_pp0_iter2_reg[2:0] <= 3'b001;
    zext_ln24_reg_915_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_1_reg_925[2:0] <= 3'b010;
    zext_ln24_1_reg_925[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_1_reg_925_pp0_iter1_reg[2:0] <= 3'b010;
    zext_ln24_1_reg_925_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_1_reg_925_pp0_iter2_reg[2:0] <= 3'b010;
    zext_ln24_1_reg_925_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_2_reg_935[2:0] <= 3'b011;
    zext_ln24_2_reg_935[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_2_reg_935_pp0_iter1_reg[2:0] <= 3'b011;
    zext_ln24_2_reg_935_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_2_reg_935_pp0_iter2_reg[2:0] <= 3'b011;
    zext_ln24_2_reg_935_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_3_reg_952[2:0] <= 3'b100;
    zext_ln24_3_reg_952[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_6_reg_962[2:0] <= 3'b111;
    zext_ln24_6_reg_962[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_6_reg_962_pp0_iter1_reg[2:0] <= 3'b111;
    zext_ln24_6_reg_962_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_6_reg_962_pp0_iter2_reg[2:0] <= 3'b111;
    zext_ln24_6_reg_962_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_4_reg_989[2:0] <= 3'b101;
    zext_ln24_4_reg_989[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_4_reg_989_pp0_iter1_reg[2:0] <= 3'b101;
    zext_ln24_4_reg_989_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_5_reg_999[2:0] <= 3'b110;
    zext_ln24_5_reg_999[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_5_reg_999_pp0_iter1_reg[2:0] <= 3'b110;
    zext_ln24_5_reg_999_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_5_reg_999_pp0_iter2_reg[2:0] <= 3'b110;
    zext_ln24_5_reg_999_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln24_5_reg_999_pp0_iter3_reg[2:0] <= 3'b110;
    zext_ln24_5_reg_999_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    tmp_16_reg_1081[12:0] <= 13'b1000000000000;
end

endmodule //dct_dct_1d
