// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_1d_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_0_val,
        src_1_val,
        src_2_val,
        src_3_val,
        src_4_val,
        src_5_val,
        src_6_val,
        src_7_val,
        dst_address0,
        dst_ce0,
        dst_we0,
        dst_d0,
        dst_address1,
        dst_ce1,
        dst_we1,
        dst_d1,
        dst_offset
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] src_0_val;
input  [15:0] src_1_val;
input  [15:0] src_2_val;
input  [15:0] src_3_val;
input  [15:0] src_4_val;
input  [15:0] src_5_val;
input  [15:0] src_6_val;
input  [15:0] src_7_val;
output  [5:0] dst_address0;
output   dst_ce0;
output   dst_we0;
output  [15:0] dst_d0;
output  [5:0] dst_address1;
output   dst_ce1;
output   dst_we1;
output  [15:0] dst_d1;
input  [2:0] dst_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg  signed [15:0] src_7_val_read_reg_881;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] src_6_val_read_reg_887;
reg  signed [15:0] src_5_val_read_reg_894;
reg  signed [15:0] src_4_val_read_reg_900;
reg  signed [15:0] src_3_val_read_reg_905;
reg  signed [15:0] src_2_val_read_reg_910;
reg  signed [15:0] src_1_val_read_reg_915;
reg  signed [15:0] src_0_val_read_reg_920;
wire  signed [16:0] sext_ln24_3_fu_201_p1;
reg  signed [16:0] sext_ln24_3_reg_926;
wire  signed [16:0] sext_ln11_1_fu_205_p1;
reg  signed [16:0] sext_ln11_1_reg_932;
wire   [15:0] tmp_fu_217_p2;
reg   [15:0] tmp_reg_937;
wire   [15:0] tmp218_fu_229_p2;
reg   [15:0] tmp218_reg_942;
wire   [28:0] tmp_10_fu_263_p2;
reg   [28:0] tmp_10_reg_947;
wire  signed [28:0] sext_ln24_11_fu_269_p1;
reg  signed [28:0] sext_ln24_11_reg_953;
wire   [28:0] mul_ln24_fu_273_p2;
reg  signed [28:0] mul_ln24_reg_958;
wire  signed [28:0] sext_ln24_13_fu_279_p1;
reg  signed [28:0] sext_ln24_13_reg_963;
wire  signed [28:0] sext_ln24_14_fu_283_p1;
reg  signed [28:0] sext_ln24_14_reg_969;
wire   [28:0] mul_ln24_3_fu_287_p2;
reg  signed [28:0] mul_ln24_3_reg_974;
wire  signed [28:0] sext_ln24_15_fu_293_p1;
reg  signed [28:0] sext_ln24_15_reg_979;
wire  signed [28:0] sext_ln24_17_fu_297_p1;
reg   [2:0] dst_offset_read_reg_991;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [2:0] dst_offset_read_reg_991_pp0_iter1_reg;
wire  signed [28:0] tmp7_cast15_fu_370_p1;
reg  signed [28:0] tmp7_cast15_reg_1002;
(* use_dsp48 = "no" *) wire   [17:0] tmp12_fu_384_p2;
reg  signed [17:0] tmp12_reg_1008;
wire  signed [28:0] tmp19_cast_fu_411_p1;
reg  signed [28:0] tmp19_cast_reg_1013;
wire  signed [28:0] tmp25_cast17_fu_421_p1;
reg  signed [28:0] tmp25_cast17_reg_1019;
reg   [15:0] trunc_ln26_4_reg_1025;
wire   [28:0] mul_ln24_7_fu_484_p2;
reg  signed [28:0] mul_ln24_7_reg_1030;
wire  signed [28:0] sext_ln26_fu_496_p1;
reg  signed [28:0] sext_ln26_reg_1035;
(* use_dsp48 = "no" *) wire   [17:0] tmp40_fu_510_p2;
reg  signed [17:0] tmp40_reg_1041;
wire   [28:0] mul_ln24_11_fu_516_p2;
reg  signed [28:0] mul_ln24_11_reg_1046;
wire  signed [28:0] sext_ln24_10_fu_534_p1;
reg  signed [28:0] sext_ln24_10_reg_1051;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire  signed [28:0] sext_ln24_12_fu_537_p1;
reg  signed [28:0] sext_ln24_12_reg_1057;
wire   [28:0] mul_ln24_1_fu_540_p2;
reg  signed [28:0] mul_ln24_1_reg_1062;
wire   [28:0] mul_ln24_5_fu_546_p2;
reg  signed [28:0] mul_ln24_5_reg_1067;
wire  signed [28:0] grp_fu_739_p4;
reg   [28:0] add_ln26_8_reg_1072;
wire    ap_block_pp0_stage3_11001;
wire   [28:0] grp_fu_731_p3;
reg  signed [28:0] add_ln26_11_reg_1077;
wire  signed [28:0] grp_fu_748_p3;
reg   [28:0] add_ln26_14_reg_1082;
wire   [28:0] mul_ln24_9_fu_554_p2;
reg  signed [28:0] mul_ln24_9_reg_1087;
wire  signed [28:0] grp_fu_755_p3;
reg   [28:0] add_ln26_19_reg_1092;
wire   [28:0] mul_ln24_13_fu_559_p2;
reg  signed [28:0] mul_ln24_13_reg_1097;
wire  signed [28:0] grp_fu_762_p3;
reg   [28:0] add_ln26_25_reg_1102;
wire  signed [28:0] grp_fu_769_p3;
reg  signed [28:0] add_ln26_10_reg_1107;
wire   [28:0] grp_fu_776_p3;
reg   [28:0] add_ln26_13_reg_1112;
wire  signed [28:0] grp_fu_784_p4;
reg  signed [28:0] add_ln26_16_reg_1117;
wire   [28:0] grp_fu_791_p3;
reg  signed [28:0] add_ln26_17_reg_1122;
wire   [28:0] grp_fu_799_p3;
reg  signed [28:0] add_ln26_22_reg_1127;
reg   [15:0] trunc_ln26_1_reg_1132;
wire  signed [28:0] grp_fu_815_p3;
reg  signed [28:0] add_ln26_21_reg_1137;
wire   [28:0] grp_fu_821_p3;
wire  signed [28:0] grp_fu_828_p3;
reg  signed [28:0] add_ln26_27_reg_1147;
wire   [28:0] grp_fu_834_p3;
reg  signed [28:0] add_ln26_28_reg_1152;
reg   [15:0] trunc_ln26_3_reg_1157;
reg   [15:0] trunc_ln26_5_reg_1162;
reg   [15:0] trunc_ln26_6_reg_1167;
reg   [15:0] trunc_ln26_7_reg_1172;
wire    ap_block_pp0_stage1_subdone;
reg   [2:0] ap_port_reg_dst_offset;
wire   [63:0] zext_ln8_fu_309_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln26_3_fu_529_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln26_1_fu_590_p1;
wire   [63:0] zext_ln26_fu_678_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln26_5_fu_690_p1;
wire   [63:0] zext_ln26_2_fu_702_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln26_4_fu_714_p1;
wire   [63:0] zext_ln26_6_fu_726_p1;
reg    dst_we1_local;
reg   [15:0] dst_d1_local;
reg    dst_ce1_local;
reg   [5:0] dst_address1_local;
reg    dst_we0_local;
reg   [15:0] dst_d0_local;
reg    dst_ce0_local;
reg   [5:0] dst_address0_local;
wire  signed [15:0] sext_ln24_3_fu_201_p0;
wire  signed [15:0] sext_ln11_1_fu_205_p0;
wire  signed [15:0] shl_ln_fu_209_p1;
wire  signed [15:0] tmp_fu_217_p0;
wire  signed [15:0] tmp_fu_217_p1;
wire  signed [15:0] tmp1_fu_223_p0;
wire  signed [15:0] tmp1_fu_223_p1;
wire   [15:0] tmp1_fu_223_p2;
wire  signed [15:0] tmp_4_fu_235_p1;
wire  signed [15:0] tmp5716_fu_243_p0;
wire  signed [15:0] tmp5716_fu_243_p1;
wire   [15:0] tmp5716_fu_243_p2;
wire   [28:0] tmp_4_fu_235_p3;
wire   [28:0] shl_ln_fu_209_p3;
wire   [28:0] add_ln24_fu_257_p2;
wire   [28:0] tmp6_fu_249_p3;
wire  signed [15:0] sext_ln24_11_fu_269_p0;
wire   [14:0] mul_ln24_fu_273_p1;
wire  signed [15:0] sext_ln24_13_fu_279_p0;
wire  signed [15:0] sext_ln24_14_fu_283_p0;
wire  signed [14:0] mul_ln24_3_fu_287_p1;
wire  signed [15:0] sext_ln24_15_fu_293_p0;
wire  signed [15:0] sext_ln24_17_fu_297_p0;
wire   [5:0] tmp_1_fu_301_p3;
wire   [28:0] tmp3_fu_341_p3;
wire   [28:0] add_ln26_fu_348_p2;
wire  signed [16:0] sext_ln24_2_fu_320_p1;
wire  signed [16:0] sext_ln24_5_fu_329_p1;
wire  signed [16:0] tmp7_fu_364_p2;
wire  signed [16:0] sext_ln24_1_fu_317_p1;
wire   [16:0] tmp11_fu_374_p2;
wire  signed [17:0] tmp11_cast_fu_380_p1;
wire  signed [17:0] sext_ln24_4_fu_326_p1;
wire  signed [16:0] sext_ln24_fu_314_p1;
wire   [16:0] tmp17_fu_390_p2;
wire  signed [17:0] tmp17_cast_fu_395_p1;
wire  signed [17:0] sext_ln11_fu_323_p1;
wire   [17:0] tmp18_fu_399_p2;
wire  signed [17:0] sext_ln24_9_fu_338_p1;
wire  signed [17:0] tmp19_fu_405_p2;
wire  signed [16:0] sext_ln24_6_fu_332_p1;
wire  signed [16:0] tmp25_fu_415_p2;
wire  signed [16:0] tmp27_fu_425_p2;
wire   [15:0] empty_fu_435_p1;
wire  signed [28:0] tmp27_cast_fu_431_p1;
wire   [28:0] p_shl1_fu_439_p3;
wire   [28:0] p_shl_fu_453_p3;
wire   [28:0] sub_ln26_fu_460_p2;
wire   [28:0] tmp28_fu_447_p2;
wire   [28:0] add_ln26_4_fu_465_p2;
wire  signed [15:0] mul_ln24_7_fu_484_p0;
wire  signed [28:0] sext_ln24_16_fu_481_p1;
wire   [14:0] mul_ln24_7_fu_484_p1;
wire  signed [16:0] sext_ln24_8_fu_335_p1;
wire  signed [16:0] tmp35_fu_490_p2;
wire   [16:0] tmp39_fu_500_p2;
wire  signed [17:0] tmp39_cast_fu_506_p1;
wire  signed [15:0] mul_ln24_11_fu_516_p0;
wire  signed [14:0] mul_ln24_11_fu_516_p1;
wire   [5:0] tmp_7_fu_522_p3;
wire  signed [14:0] mul_ln24_1_fu_540_p1;
wire  signed [15:0] mul_ln24_5_fu_546_p0;
wire  signed [14:0] mul_ln24_5_fu_546_p1;
wire  signed [15:0] mul_ln24_9_fu_554_p0;
wire   [14:0] mul_ln24_9_fu_554_p1;
wire  signed [15:0] mul_ln24_13_fu_559_p0;
wire  signed [14:0] mul_ln24_13_fu_559_p1;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_12_fu_564_p2;
wire  signed [28:0] add_ln26_1_fu_568_p1;
wire   [28:0] grp_fu_807_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_1_fu_568_p2;
wire   [5:0] tmp_3_fu_583_p3;
wire  signed [28:0] trunc_ln26_2_fu_595_p1;
wire   [28:0] grp_fu_841_p4;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_18_fu_605_p2;
wire  signed [28:0] add_ln26_3_fu_609_p1;
wire   [28:0] grp_fu_850_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_3_fu_609_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_23_fu_624_p2;
wire  signed [28:0] add_ln26_5_fu_628_p1;
wire   [28:0] grp_fu_857_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_5_fu_628_p2;
wire  signed [28:0] trunc_ln26_6_fu_643_p1;
wire   [28:0] grp_fu_864_p4;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_29_fu_652_p2;
wire  signed [28:0] add_ln26_7_fu_656_p1;
wire   [28:0] grp_fu_874_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln26_7_fu_656_p2;
wire   [5:0] tmp_2_fu_671_p3;
wire   [5:0] tmp_9_fu_683_p3;
wire   [5:0] tmp_6_fu_695_p3;
wire   [5:0] tmp_8_fu_707_p3;
wire   [5:0] tmp_s_fu_719_p3;
wire  signed [14:0] grp_fu_731_p1;
wire   [12:0] grp_fu_731_p2;
wire   [11:0] grp_fu_739_p2;
wire   [13:0] grp_fu_748_p1;
wire  signed [15:0] grp_fu_755_p0;
wire  signed [14:0] grp_fu_755_p1;
wire  signed [15:0] grp_fu_762_p0;
wire   [13:0] grp_fu_762_p1;
wire   [12:0] grp_fu_769_p1;
wire   [13:0] grp_fu_776_p1;
wire   [12:0] grp_fu_776_p2;
wire  signed [15:0] grp_fu_784_p0;
wire  signed [15:0] grp_fu_784_p1;
wire   [12:0] grp_fu_784_p2;
wire   [11:0] grp_fu_791_p1;
wire   [12:0] grp_fu_791_p2;
wire   [12:0] grp_fu_799_p1;
wire   [12:0] grp_fu_799_p2;
wire   [13:0] grp_fu_807_p1;
wire  signed [16:0] grp_fu_815_p0;
wire   [11:0] grp_fu_815_p1;
wire  signed [17:0] grp_fu_821_p0;
wire   [12:0] grp_fu_821_p1;
wire   [12:0] grp_fu_821_p2;
wire  signed [16:0] grp_fu_828_p0;
wire   [12:0] grp_fu_828_p1;
wire  signed [16:0] grp_fu_834_p0;
wire   [11:0] grp_fu_834_p1;
wire   [12:0] grp_fu_834_p2;
wire  signed [15:0] grp_fu_841_p1;
wire  signed [17:0] sext_ln24_7_fu_551_p1;
wire   [12:0] grp_fu_841_p2;
wire  signed [15:0] grp_fu_850_p0;
wire   [13:0] grp_fu_850_p1;
wire  signed [15:0] grp_fu_857_p0;
wire  signed [14:0] grp_fu_857_p1;
wire  signed [15:0] grp_fu_864_p1;
wire   [13:0] grp_fu_864_p2;
wire  signed [15:0] grp_fu_874_p0;
wire   [13:0] grp_fu_874_p1;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U10(
    .din0(sext_ln24_11_fu_269_p0),
    .din1(mul_ln24_fu_273_p1),
    .dout(mul_ln24_fu_273_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U11(
    .din0(sext_ln24_14_fu_283_p0),
    .din1(mul_ln24_3_fu_287_p1),
    .dout(mul_ln24_3_fu_287_p2)
);

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U12(
    .din0(mul_ln24_7_fu_484_p0),
    .din1(mul_ln24_7_fu_484_p1),
    .dout(mul_ln24_7_fu_484_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U13(
    .din0(mul_ln24_11_fu_516_p0),
    .din1(mul_ln24_11_fu_516_p1),
    .dout(mul_ln24_11_fu_516_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U14(
    .din0(src_6_val_read_reg_887),
    .din1(mul_ln24_1_fu_540_p1),
    .dout(mul_ln24_1_fu_540_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U15(
    .din0(mul_ln24_5_fu_546_p0),
    .din1(mul_ln24_5_fu_546_p1),
    .dout(mul_ln24_5_fu_546_p2)
);

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U16(
    .din0(mul_ln24_9_fu_554_p0),
    .din1(mul_ln24_9_fu_554_p1),
    .dout(mul_ln24_9_fu_554_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U17(
    .din0(mul_ln24_13_fu_559_p0),
    .din1(mul_ln24_13_fu_559_p1),
    .dout(mul_ln24_13_fu_559_p2)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln24_13_fu_279_p0),
    .din1(grp_fu_731_p1),
    .din2(grp_fu_731_p2),
    .ce(1'b1),
    .dout(grp_fu_731_p3)
);

dct_ama_submuladd_16s_16s_12ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_12ns_29s_29_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln24_3_fu_201_p0),
    .din1(sext_ln11_1_fu_205_p0),
    .din2(grp_fu_739_p2),
    .din3(mul_ln24_reg_958),
    .ce(1'b1),
    .dout(grp_fu_739_p4)
);

dct_mac_muladd_16s_14ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln24_15_fu_293_p0),
    .din1(grp_fu_748_p1),
    .din2(mul_ln24_3_reg_974),
    .ce(1'b1),
    .dout(grp_fu_748_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_755_p0),
    .din1(grp_fu_755_p1),
    .din2(mul_ln24_7_reg_1030),
    .ce(1'b1),
    .dout(grp_fu_755_p3)
);

dct_mac_muladd_16s_14ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_762_p0),
    .din1(grp_fu_762_p1),
    .din2(mul_ln24_11_reg_1046),
    .ce(1'b1),
    .dout(grp_fu_762_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp7_fu_364_p2),
    .din1(grp_fu_769_p1),
    .din2(mul_ln24_1_reg_1062),
    .ce(1'b1),
    .dout(grp_fu_769_p3)
);

dct_mac_muladd_18s_14ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_14ns_13ns_29_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp19_fu_405_p2),
    .din1(grp_fu_776_p1),
    .din2(grp_fu_776_p2),
    .ce(1'b1),
    .dout(grp_fu_776_p3)
);

dct_ama_submuladd_16s_16s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_13ns_29s_29_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_784_p0),
    .din1(grp_fu_784_p1),
    .din2(grp_fu_784_p2),
    .din3(mul_ln24_5_reg_1067),
    .ce(1'b1),
    .dout(grp_fu_784_p4)
);

dct_mac_muladd_17s_12ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp25_fu_415_p2),
    .din1(grp_fu_791_p1),
    .din2(grp_fu_791_p2),
    .ce(1'b1),
    .dout(grp_fu_791_p3)
);

dct_mac_muladd_17s_13ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_13ns_29_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp35_fu_490_p2),
    .din1(grp_fu_799_p1),
    .din2(grp_fu_799_p2),
    .ce(1'b1),
    .dout(grp_fu_799_p3)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(src_0_val_read_reg_920),
    .din1(grp_fu_807_p1),
    .din2(add_ln26_8_reg_1072),
    .ce(1'b1),
    .dout(grp_fu_807_p3)
);

dct_mac_muladd_17s_12ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_29s_29_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_815_p0),
    .din1(grp_fu_815_p1),
    .din2(mul_ln24_9_reg_1087),
    .ce(1'b1),
    .dout(grp_fu_815_p3)
);

dct_mac_muladd_18s_13ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_13ns_13ns_29_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_821_p0),
    .din1(grp_fu_821_p1),
    .din2(grp_fu_821_p2),
    .ce(1'b1),
    .dout(grp_fu_821_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_828_p0),
    .din1(grp_fu_828_p1),
    .din2(mul_ln24_13_reg_1097),
    .ce(1'b1),
    .dout(grp_fu_828_p3)
);

dct_mac_muladd_17s_12ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_834_p0),
    .din1(grp_fu_834_p1),
    .din2(grp_fu_834_p2),
    .ce(1'b1),
    .dout(grp_fu_834_p3)
);

dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_18s_16s_13ns_29ns_29_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp12_reg_1008),
    .din1(grp_fu_841_p1),
    .din2(grp_fu_841_p2),
    .din3(add_ln26_13_reg_1112),
    .ce(1'b1),
    .dout(grp_fu_841_p4)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_850_p0),
    .din1(grp_fu_850_p1),
    .din2(add_ln26_14_reg_1082),
    .ce(1'b1),
    .dout(grp_fu_850_p3)
);

dct_mac_muladd_16s_15s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29ns_29_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_857_p0),
    .din1(grp_fu_857_p1),
    .din2(add_ln26_19_reg_1092),
    .ce(1'b1),
    .dout(grp_fu_857_p3)
);

dct_ama_submuladd_18s_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_18s_16s_14ns_29ns_29_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp40_reg_1041),
    .din1(grp_fu_864_p1),
    .din2(grp_fu_864_p2),
    .din3(grp_fu_821_p3),
    .ce(1'b1),
    .dout(grp_fu_864_p4)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_874_p0),
    .din1(grp_fu_874_p1),
    .din2(add_ln26_25_reg_1102),
    .ce(1'b1),
    .dout(grp_fu_874_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln26_10_reg_1107 <= grp_fu_769_p3;
        add_ln26_13_reg_1112 <= grp_fu_776_p3;
        add_ln26_16_reg_1117 <= grp_fu_784_p4;
        add_ln26_17_reg_1122 <= grp_fu_791_p3;
        add_ln26_22_reg_1127 <= grp_fu_799_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln26_11_reg_1077 <= grp_fu_731_p3;
        add_ln26_14_reg_1082 <= grp_fu_748_p3;
        add_ln26_19_reg_1092 <= grp_fu_755_p3;
        add_ln26_25_reg_1102 <= grp_fu_762_p3;
        add_ln26_8_reg_1072 <= grp_fu_739_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln26_21_reg_1137 <= grp_fu_815_p3;
        add_ln26_27_reg_1147 <= grp_fu_828_p3;
        add_ln26_28_reg_1152 <= grp_fu_834_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_dst_offset <= dst_offset;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_offset_read_reg_991 <= ap_port_reg_dst_offset;
        dst_offset_read_reg_991_pp0_iter1_reg <= dst_offset_read_reg_991;
        mul_ln24_11_reg_1046 <= mul_ln24_11_fu_516_p2;
        mul_ln24_7_reg_1030 <= mul_ln24_7_fu_484_p2;
        sext_ln26_reg_1035 <= sext_ln26_fu_496_p1;
        tmp12_reg_1008 <= tmp12_fu_384_p2;
        tmp19_cast_reg_1013 <= tmp19_cast_fu_411_p1;
        tmp25_cast17_reg_1019 <= tmp25_cast17_fu_421_p1;
        tmp40_reg_1041 <= tmp40_fu_510_p2;
        tmp7_cast15_reg_1002 <= tmp7_cast15_fu_370_p1;
        trunc_ln26_1_reg_1132 <= {{add_ln26_1_fu_568_p2[28:13]}};
        trunc_ln26_4_reg_1025 <= {{add_ln26_4_fu_465_p2[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_ln24_13_reg_1097 <= mul_ln24_13_fu_559_p2;
        mul_ln24_9_reg_1087 <= mul_ln24_9_fu_554_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln24_1_reg_1062 <= mul_ln24_1_fu_540_p2;
        mul_ln24_5_reg_1067 <= mul_ln24_5_fu_546_p2;
        sext_ln24_10_reg_1051 <= sext_ln24_10_fu_534_p1;
        sext_ln24_12_reg_1057 <= sext_ln24_12_fu_537_p1;
        trunc_ln26_3_reg_1157 <= {{add_ln26_3_fu_609_p2[28:13]}};
        trunc_ln26_5_reg_1162 <= {{add_ln26_5_fu_628_p2[28:13]}};
        trunc_ln26_6_reg_1167 <= {{trunc_ln26_6_fu_643_p1[28:13]}};
        trunc_ln26_7_reg_1172 <= {{add_ln26_7_fu_656_p2[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln24_3_reg_974 <= mul_ln24_3_fu_287_p2;
        mul_ln24_reg_958 <= mul_ln24_fu_273_p2;
        sext_ln11_1_reg_932 <= sext_ln11_1_fu_205_p1;
        sext_ln24_11_reg_953 <= sext_ln24_11_fu_269_p1;
        sext_ln24_13_reg_963 <= sext_ln24_13_fu_279_p1;
        sext_ln24_14_reg_969 <= sext_ln24_14_fu_283_p1;
        sext_ln24_15_reg_979 <= sext_ln24_15_fu_293_p1;
        sext_ln24_3_reg_926 <= sext_ln24_3_fu_201_p1;
        src_0_val_read_reg_920 <= src_0_val;
        src_1_val_read_reg_915 <= src_1_val;
        src_2_val_read_reg_910 <= src_2_val;
        src_3_val_read_reg_905 <= src_3_val;
        src_4_val_read_reg_900 <= src_4_val;
        src_5_val_read_reg_894 <= src_5_val;
        src_6_val_read_reg_887 <= src_6_val;
        src_7_val_read_reg_881 <= src_7_val;
        tmp218_reg_942 <= tmp218_fu_229_p2;
        tmp_10_reg_947[28 : 13] <= tmp_10_fu_263_p2[28 : 13];
        tmp_reg_937 <= tmp_fu_217_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_address0_local = zext_ln26_6_fu_726_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_address0_local = zext_ln26_4_fu_714_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_address0_local = zext_ln26_5_fu_690_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_address0_local = zext_ln26_1_fu_590_p1;
    end else begin
        dst_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_address1_local = zext_ln26_2_fu_702_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_address1_local = zext_ln26_fu_678_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_address1_local = zext_ln26_3_fu_529_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_address1_local = zext_ln8_fu_309_p1;
    end else begin
        dst_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        dst_ce0_local = 1'b1;
    end else begin
        dst_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        dst_ce1_local = 1'b1;
    end else begin
        dst_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_d0_local = trunc_ln26_7_reg_1172;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_d0_local = trunc_ln26_5_reg_1162;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_d0_local = trunc_ln26_6_reg_1167;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_d0_local = {{trunc_ln26_2_fu_595_p1[28:13]}};
    end else begin
        dst_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_d1_local = trunc_ln26_3_reg_1157;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_d1_local = trunc_ln26_1_reg_1132;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_d1_local = trunc_ln26_4_reg_1025;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_d1_local = {{add_ln26_fu_348_p2[28:13]}};
    end else begin
        dst_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        dst_we0_local = 1'b1;
    end else begin
        dst_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        dst_we1_local = 1'b1;
    end else begin
        dst_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_257_p2 = (tmp_4_fu_235_p3 + shl_ln_fu_209_p3);

assign add_ln26_12_fu_564_p2 = ($signed(add_ln26_11_reg_1077) + $signed(add_ln26_10_reg_1107));

assign add_ln26_18_fu_605_p2 = ($signed(add_ln26_17_reg_1122) + $signed(add_ln26_16_reg_1117));

assign add_ln26_1_fu_568_p1 = grp_fu_807_p3;

assign add_ln26_1_fu_568_p2 = ($signed(add_ln26_12_fu_564_p2) + $signed(add_ln26_1_fu_568_p1));

assign add_ln26_23_fu_624_p2 = ($signed(add_ln26_22_reg_1127) + $signed(add_ln26_21_reg_1137));

assign add_ln26_29_fu_652_p2 = ($signed(add_ln26_28_reg_1152) + $signed(add_ln26_27_reg_1147));

assign add_ln26_3_fu_609_p1 = grp_fu_850_p3;

assign add_ln26_3_fu_609_p2 = ($signed(add_ln26_18_fu_605_p2) + $signed(add_ln26_3_fu_609_p1));

assign add_ln26_4_fu_465_p2 = (sub_ln26_fu_460_p2 + tmp28_fu_447_p2);

assign add_ln26_5_fu_628_p1 = grp_fu_857_p3;

assign add_ln26_5_fu_628_p2 = ($signed(add_ln26_23_fu_624_p2) + $signed(add_ln26_5_fu_628_p1));

assign add_ln26_7_fu_656_p1 = grp_fu_874_p3;

assign add_ln26_7_fu_656_p2 = ($signed(add_ln26_29_fu_652_p2) + $signed(add_ln26_7_fu_656_p1));

assign add_ln26_fu_348_p2 = (tmp_10_reg_947 + tmp3_fu_341_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign dst_address0 = dst_address0_local;

assign dst_address1 = dst_address1_local;

assign dst_ce0 = dst_ce0_local;

assign dst_ce1 = dst_ce1_local;

assign dst_d0 = dst_d0_local;

assign dst_d1 = dst_d1_local;

assign dst_we0 = dst_we0_local;

assign dst_we1 = dst_we1_local;

assign empty_fu_435_p1 = tmp27_fu_425_p2[15:0];

assign grp_fu_731_p1 = 29'd536859550;

assign grp_fu_731_p2 = 29'd4096;

assign grp_fu_739_p2 = 29'd2260;

assign grp_fu_748_p1 = 29'd11363;

assign grp_fu_755_p0 = sext_ln24_17_fu_297_p1;

assign grp_fu_755_p1 = 29'd536861280;

assign grp_fu_762_p0 = sext_ln24_17_fu_297_p1;

assign grp_fu_762_p1 = 29'd11363;

assign grp_fu_769_p1 = 29'd6436;

assign grp_fu_776_p1 = 29'd10703;

assign grp_fu_776_p2 = 29'd4096;

assign grp_fu_784_p0 = sext_ln11_1_reg_932;

assign grp_fu_784_p1 = sext_ln24_3_reg_926;

assign grp_fu_784_p2 = 29'd6436;

assign grp_fu_791_p1 = 29'd2260;

assign grp_fu_791_p2 = 29'd4096;

assign grp_fu_799_p1 = 29'd6436;

assign grp_fu_799_p2 = 29'd4096;

assign grp_fu_807_p1 = 29'd11363;

assign grp_fu_815_p0 = tmp7_cast15_reg_1002;

assign grp_fu_815_p1 = 29'd2260;

assign grp_fu_821_p0 = tmp19_cast_reg_1013;

assign grp_fu_821_p1 = 29'd4433;

assign grp_fu_821_p2 = 29'd4096;

assign grp_fu_828_p0 = tmp25_cast17_reg_1019;

assign grp_fu_828_p1 = 29'd6436;

assign grp_fu_834_p0 = sext_ln26_reg_1035;

assign grp_fu_834_p1 = 29'd2260;

assign grp_fu_834_p2 = 29'd4096;

assign grp_fu_841_p1 = sext_ln24_7_fu_551_p1;

assign grp_fu_841_p2 = 29'd4433;

assign grp_fu_850_p0 = sext_ln24_10_reg_1051;

assign grp_fu_850_p1 = 29'd9633;

assign grp_fu_857_p0 = sext_ln24_11_reg_953;

assign grp_fu_857_p1 = 29'd536859550;

assign grp_fu_864_p1 = sext_ln24_7_fu_551_p1;

assign grp_fu_864_p2 = 29'd10703;

assign grp_fu_874_p0 = sext_ln24_14_reg_969;

assign grp_fu_874_p1 = 29'd9633;

assign mul_ln24_11_fu_516_p0 = sext_ln24_16_fu_481_p1;

assign mul_ln24_11_fu_516_p1 = 29'd536859550;

assign mul_ln24_13_fu_559_p0 = sext_ln24_15_reg_979;

assign mul_ln24_13_fu_559_p1 = 29'd536861280;

assign mul_ln24_1_fu_540_p1 = 29'd536861280;

assign mul_ln24_3_fu_287_p1 = 29'd536859550;

assign mul_ln24_5_fu_546_p0 = sext_ln24_13_reg_963;

assign mul_ln24_5_fu_546_p1 = 29'd536861280;

assign mul_ln24_7_fu_484_p0 = sext_ln24_16_fu_481_p1;

assign mul_ln24_7_fu_484_p1 = 29'd9633;

assign mul_ln24_9_fu_554_p0 = sext_ln24_12_reg_1057;

assign mul_ln24_9_fu_554_p1 = 29'd11363;

assign mul_ln24_fu_273_p1 = 29'd9633;

assign p_shl1_fu_439_p3 = {{empty_fu_435_p1}, {13'd0}};

assign p_shl_fu_453_p3 = {{tmp_reg_937}, {13'd0}};

assign sext_ln11_1_fu_205_p0 = src_4_val;

assign sext_ln11_1_fu_205_p1 = sext_ln11_1_fu_205_p0;

assign sext_ln11_fu_323_p1 = src_4_val_read_reg_900;

assign sext_ln24_10_fu_534_p1 = src_0_val_read_reg_920;

assign sext_ln24_11_fu_269_p0 = src_1_val;

assign sext_ln24_11_fu_269_p1 = sext_ln24_11_fu_269_p0;

assign sext_ln24_12_fu_537_p1 = src_6_val_read_reg_887;

assign sext_ln24_13_fu_279_p0 = src_7_val;

assign sext_ln24_13_fu_279_p1 = sext_ln24_13_fu_279_p0;

assign sext_ln24_14_fu_283_p0 = src_2_val;

assign sext_ln24_14_fu_283_p1 = sext_ln24_14_fu_283_p0;

assign sext_ln24_15_fu_293_p0 = src_5_val;

assign sext_ln24_15_fu_293_p1 = sext_ln24_15_fu_293_p0;

assign sext_ln24_16_fu_481_p1 = src_3_val_read_reg_905;

assign sext_ln24_17_fu_297_p0 = src_4_val;

assign sext_ln24_17_fu_297_p1 = sext_ln24_17_fu_297_p0;

assign sext_ln24_1_fu_317_p1 = src_1_val_read_reg_915;

assign sext_ln24_2_fu_320_p1 = src_2_val_read_reg_910;

assign sext_ln24_3_fu_201_p0 = src_3_val;

assign sext_ln24_3_fu_201_p1 = sext_ln24_3_fu_201_p0;

assign sext_ln24_4_fu_326_p1 = src_5_val_read_reg_894;

assign sext_ln24_5_fu_329_p1 = src_5_val_read_reg_894;

assign sext_ln24_6_fu_332_p1 = src_6_val_read_reg_887;

assign sext_ln24_7_fu_551_p1 = src_6_val_read_reg_887;

assign sext_ln24_8_fu_335_p1 = src_7_val_read_reg_881;

assign sext_ln24_9_fu_338_p1 = src_7_val_read_reg_881;

assign sext_ln24_fu_314_p1 = src_0_val_read_reg_920;

assign sext_ln26_fu_496_p1 = tmp35_fu_490_p2;

assign shl_ln_fu_209_p1 = src_7_val;

assign shl_ln_fu_209_p3 = {{shl_ln_fu_209_p1}, {13'd0}};

assign sub_ln26_fu_460_p2 = (tmp_10_reg_947 - p_shl_fu_453_p3);

assign tmp11_cast_fu_380_p1 = $signed(tmp11_fu_374_p2);

assign tmp11_fu_374_p2 = ($signed(sext_ln24_1_fu_317_p1) - $signed(sext_ln24_2_fu_320_p1));

assign tmp12_fu_384_p2 = ($signed(tmp11_cast_fu_380_p1) - $signed(sext_ln24_4_fu_326_p1));

assign tmp17_cast_fu_395_p1 = $signed(tmp17_fu_390_p2);

assign tmp17_fu_390_p2 = ($signed(sext_ln24_fu_314_p1) - $signed(sext_ln24_3_reg_926));

assign tmp18_fu_399_p2 = ($signed(tmp17_cast_fu_395_p1) - $signed(sext_ln11_fu_323_p1));

assign tmp19_cast_fu_411_p1 = tmp19_fu_405_p2;

assign tmp19_fu_405_p2 = ($signed(tmp18_fu_399_p2) + $signed(sext_ln24_9_fu_338_p1));

assign tmp1_fu_223_p0 = src_5_val;

assign tmp1_fu_223_p1 = src_6_val;

assign tmp1_fu_223_p2 = ($signed(tmp1_fu_223_p0) + $signed(tmp1_fu_223_p1));

assign tmp218_fu_229_p2 = (tmp1_fu_223_p2 + tmp_fu_217_p2);

assign tmp25_cast17_fu_421_p1 = tmp25_fu_415_p2;

assign tmp25_fu_415_p2 = ($signed(sext_ln24_6_fu_332_p1) - $signed(sext_ln24_1_fu_317_p1));

assign tmp27_cast_fu_431_p1 = tmp27_fu_425_p2;

assign tmp27_fu_425_p2 = ($signed(sext_ln24_6_fu_332_p1) + $signed(sext_ln24_5_fu_329_p1));

assign tmp28_fu_447_p2 = ($signed(tmp27_cast_fu_431_p1) - $signed(p_shl1_fu_439_p3));

assign tmp35_fu_490_p2 = ($signed(sext_ln24_fu_314_p1) - $signed(sext_ln24_8_fu_335_p1));

assign tmp39_cast_fu_506_p1 = $signed(tmp39_fu_500_p2);

assign tmp39_fu_500_p2 = ($signed(sext_ln24_2_fu_320_p1) - $signed(sext_ln24_1_fu_317_p1));

assign tmp3_fu_341_p3 = {{tmp218_reg_942}, {13'd0}};

assign tmp40_fu_510_p2 = ($signed(tmp39_cast_fu_506_p1) + $signed(sext_ln24_4_fu_326_p1));

assign tmp5716_fu_243_p0 = src_4_val;

assign tmp5716_fu_243_p1 = src_3_val;

assign tmp5716_fu_243_p2 = ($signed(tmp5716_fu_243_p0) + $signed(tmp5716_fu_243_p1));

assign tmp6_fu_249_p3 = {{tmp5716_fu_243_p2}, {13'd0}};

assign tmp7_cast15_fu_370_p1 = tmp7_fu_364_p2;

assign tmp7_fu_364_p2 = ($signed(sext_ln24_2_fu_320_p1) - $signed(sext_ln24_5_fu_329_p1));

assign tmp_10_fu_263_p2 = (add_ln24_fu_257_p2 + tmp6_fu_249_p3);

assign tmp_1_fu_301_p3 = {{ap_port_reg_dst_offset}, {3'd0}};

assign tmp_2_fu_671_p3 = {{dst_offset_read_reg_991_pp0_iter1_reg}, {3'd1}};

assign tmp_3_fu_583_p3 = {{dst_offset_read_reg_991_pp0_iter1_reg}, {3'd2}};

assign tmp_4_fu_235_p1 = src_0_val;

assign tmp_4_fu_235_p3 = {{tmp_4_fu_235_p1}, {13'd4096}};

assign tmp_6_fu_695_p3 = {{dst_offset_read_reg_991_pp0_iter1_reg}, {3'd3}};

assign tmp_7_fu_522_p3 = {{dst_offset_read_reg_991}, {3'd4}};

assign tmp_8_fu_707_p3 = {{dst_offset_read_reg_991_pp0_iter1_reg}, {3'd5}};

assign tmp_9_fu_683_p3 = {{dst_offset_read_reg_991_pp0_iter1_reg}, {3'd6}};

assign tmp_fu_217_p0 = src_2_val;

assign tmp_fu_217_p1 = src_1_val;

assign tmp_fu_217_p2 = ($signed(tmp_fu_217_p0) + $signed(tmp_fu_217_p1));

assign tmp_s_fu_719_p3 = {{dst_offset_read_reg_991_pp0_iter1_reg}, {3'd7}};

assign trunc_ln26_2_fu_595_p1 = grp_fu_841_p4;

assign trunc_ln26_6_fu_643_p1 = grp_fu_864_p4;

assign zext_ln26_1_fu_590_p1 = tmp_3_fu_583_p3;

assign zext_ln26_2_fu_702_p1 = tmp_6_fu_695_p3;

assign zext_ln26_3_fu_529_p1 = tmp_7_fu_522_p3;

assign zext_ln26_4_fu_714_p1 = tmp_8_fu_707_p3;

assign zext_ln26_5_fu_690_p1 = tmp_9_fu_683_p3;

assign zext_ln26_6_fu_726_p1 = tmp_s_fu_719_p3;

assign zext_ln26_fu_678_p1 = tmp_2_fu_671_p3;

assign zext_ln8_fu_309_p1 = tmp_1_fu_301_p3;

always @ (posedge ap_clk) begin
    tmp_10_reg_947[12:0] <= 13'b1000000000000;
end

endmodule //dct_dct_1d_1
