// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sha3_256_hw_KeccakF1600_StatePermute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_address0,
        state_ce0,
        state_we0,
        state_d0,
        state_q0,
        state_address1,
        state_ce1,
        state_we1,
        state_d1,
        state_q1
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] state_address0;
output   state_ce0;
output   state_we0;
output  [63:0] state_d0;
input  [63:0] state_q0;
output  [4:0] state_address1;
output   state_ce1;
output   state_we1;
output  [63:0] state_d1;
input  [63:0] state_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] state_addr_reg_698;
reg   [63:0] Aba_reg_703;
wire    ap_CS_fsm_state2;
wire   [4:0] state_addr_25_reg_708;
wire   [4:0] state_addr_26_reg_713;
reg   [63:0] Abe_reg_718;
wire    ap_CS_fsm_state3;
reg   [63:0] Abi_reg_723;
reg   [63:0] Abo_reg_740;
wire    ap_CS_fsm_state4;
reg   [63:0] Abu_reg_745;
reg   [63:0] Aga_reg_762;
wire    ap_CS_fsm_state5;
reg   [63:0] Age_reg_767;
reg   [63:0] Agi_reg_784;
wire    ap_CS_fsm_state6;
reg   [63:0] Ago_reg_789;
reg   [63:0] Agu_reg_806;
wire    ap_CS_fsm_state7;
reg   [63:0] Aka_reg_811;
reg   [63:0] Ake_reg_828;
wire    ap_CS_fsm_state8;
reg   [63:0] Aki_reg_833;
reg   [63:0] Ako_reg_850;
wire    ap_CS_fsm_state9;
reg   [63:0] Aku_reg_855;
reg   [63:0] Ama_reg_872;
wire    ap_CS_fsm_state10;
reg   [63:0] Ame_reg_877;
reg   [63:0] Ami_reg_894;
wire    ap_CS_fsm_state11;
reg   [63:0] Amo_reg_899;
reg   [63:0] Amu_reg_916;
wire    ap_CS_fsm_state12;
reg   [63:0] Asa_reg_921;
reg   [63:0] Ase_reg_938;
wire    ap_CS_fsm_state13;
reg   [63:0] Asi_reg_943;
wire   [4:0] state_addr_48_reg_954;
reg   [63:0] Aso_reg_959;
wire    ap_CS_fsm_state14;
reg   [63:0] Asu_reg_964;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_done;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_idle;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_ready;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asu_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asu_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aba_5_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aba_5_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abe_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abe_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abi_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abi_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abo_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abo_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abu_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abu_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aga_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aga_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Age_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Age_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agi_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agi_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ago_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ago_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agu_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agu_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aka_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aka_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ake_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ake_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aki_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aki_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ako_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ako_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aku_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aku_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ama_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ama_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ame_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ame_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ami_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ami_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amo_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amo_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amu_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amu_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asa_4_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asa_4_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ase_03_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ase_03_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asi_02_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asi_02_out_ap_vld;
wire   [63:0] grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aso_01_out;
wire    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aso_01_out_ap_vld;
reg    grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state28;
reg    state_ce0_local;
reg   [4:0] state_address0_local;
reg    state_ce1_local;
reg   [4:0] state_address1_local;
reg    state_we0_local;
reg   [63:0] state_d0_local;
reg    state_we1_local;
reg   [63:0] state_d1_local;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start_reg = 1'b0;
end

sha3_256_hw_KeccakF1600_StatePermute_Pipeline_state_permute grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start),
    .ap_done(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_done),
    .ap_idle(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_idle),
    .ap_ready(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_ready),
    .Asu(Asu_reg_964),
    .Aba(Aba_reg_703),
    .Abe(Abe_reg_718),
    .Abi(Abi_reg_723),
    .Abo(Abo_reg_740),
    .Abu(Abu_reg_745),
    .Aga(Aga_reg_762),
    .Age(Age_reg_767),
    .Agi(Agi_reg_784),
    .Ago(Ago_reg_789),
    .Agu(Agu_reg_806),
    .Aka(Aka_reg_811),
    .Ake(Ake_reg_828),
    .Aki(Aki_reg_833),
    .Ako(Ako_reg_850),
    .Aku(Aku_reg_855),
    .Ama(Ama_reg_872),
    .Ame(Ame_reg_877),
    .Ami(Ami_reg_894),
    .Amo(Amo_reg_899),
    .Amu(Amu_reg_916),
    .Asa(Asa_reg_921),
    .Ase(Ase_reg_938),
    .Asi(Asi_reg_943),
    .Aso(Aso_reg_959),
    .Asu_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asu_4_out),
    .Asu_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asu_4_out_ap_vld),
    .Aba_5_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aba_5_out),
    .Aba_5_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aba_5_out_ap_vld),
    .Abe_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abe_4_out),
    .Abe_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abe_4_out_ap_vld),
    .Abi_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abi_4_out),
    .Abi_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abi_4_out_ap_vld),
    .Abo_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abo_4_out),
    .Abo_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abo_4_out_ap_vld),
    .Abu_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abu_4_out),
    .Abu_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abu_4_out_ap_vld),
    .Aga_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aga_4_out),
    .Aga_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aga_4_out_ap_vld),
    .Age_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Age_4_out),
    .Age_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Age_4_out_ap_vld),
    .Agi_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agi_4_out),
    .Agi_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agi_4_out_ap_vld),
    .Ago_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ago_4_out),
    .Ago_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ago_4_out_ap_vld),
    .Agu_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agu_4_out),
    .Agu_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agu_4_out_ap_vld),
    .Aka_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aka_4_out),
    .Aka_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aka_4_out_ap_vld),
    .Ake_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ake_4_out),
    .Ake_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ake_4_out_ap_vld),
    .Aki_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aki_4_out),
    .Aki_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aki_4_out_ap_vld),
    .Ako_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ako_4_out),
    .Ako_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ako_4_out_ap_vld),
    .Aku_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aku_4_out),
    .Aku_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aku_4_out_ap_vld),
    .Ama_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ama_4_out),
    .Ama_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ama_4_out_ap_vld),
    .Ame_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ame_4_out),
    .Ame_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ame_4_out_ap_vld),
    .Ami_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ami_4_out),
    .Ami_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ami_4_out_ap_vld),
    .Amo_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amo_4_out),
    .Amo_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amo_4_out_ap_vld),
    .Amu_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amu_4_out),
    .Amu_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amu_4_out_ap_vld),
    .Asa_4_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asa_4_out),
    .Asa_4_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asa_4_out_ap_vld),
    .Ase_03_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ase_03_out),
    .Ase_03_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ase_03_out_ap_vld),
    .Asi_02_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asi_02_out),
    .Asi_02_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asi_02_out_ap_vld),
    .Aso_01_out(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aso_01_out),
    .Aso_01_out_ap_vld(grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aso_01_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start_reg <= 1'b1;
        end else if ((grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_ready == 1'b1)) begin
            grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Aba_reg_703 <= state_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Abe_reg_718 <= state_q1;
        Abi_reg_723 <= state_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Abo_reg_740 <= state_q0;
        Abu_reg_745 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Aga_reg_762 <= state_q0;
        Age_reg_767 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Agi_reg_784 <= state_q0;
        Ago_reg_789 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Agu_reg_806 <= state_q0;
        Aka_reg_811 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Ake_reg_828 <= state_q0;
        Aki_reg_833 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Ako_reg_850 <= state_q0;
        Aku_reg_855 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        Ama_reg_872 <= state_q0;
        Ame_reg_877 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        Ami_reg_894 <= state_q0;
        Amo_reg_899 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        Amu_reg_916 <= state_q0;
        Asa_reg_921 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        Ase_reg_938 <= state_q0;
        Asi_reg_943 <= state_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        Aso_reg_959 <= state_q0;
        Asu_reg_964 <= state_q1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        state_address0_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        state_address0_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        state_address0_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        state_address0_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        state_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        state_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        state_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        state_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        state_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        state_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        state_address0_local = state_addr_26_reg_713;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        state_address0_local = state_addr_reg_698;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        state_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        state_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        state_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        state_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        state_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        state_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        state_address0_local = 64'd0;
    end else begin
        state_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        state_address1_local = state_addr_48_reg_954;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        state_address1_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        state_address1_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        state_address1_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        state_address1_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        state_address1_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        state_address1_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        state_address1_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        state_address1_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        state_address1_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        state_address1_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        state_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        state_address1_local = state_addr_25_reg_708;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        state_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        state_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        state_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        state_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        state_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        state_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_address1_local = 64'd1;
    end else begin
        state_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        state_ce0_local = 1'b1;
    end else begin
        state_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        state_ce1_local = 1'b1;
    end else begin
        state_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asi_02_out;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asa_4_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amo_4_out;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ame_4_out;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aku_4_out;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aki_4_out;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aka_4_out;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ago_4_out;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Age_4_out;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abu_4_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abi_4_out;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        state_d0_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aba_5_out;
    end else begin
        state_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Asu_4_out;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aso_01_out;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ase_03_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Amu_4_out;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ami_4_out;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ama_4_out;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ako_4_out;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Ake_4_out;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agu_4_out;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Agi_4_out;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Aga_4_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abo_4_out;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        state_d1_local = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_Abe_4_out;
    end else begin
        state_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state27))) begin
        state_we0_local = 1'b1;
    end else begin
        state_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state27))) begin
        state_we1_local = 1'b1;
    end else begin
        state_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start = grp_KeccakF1600_StatePermute_Pipeline_state_permute_fu_390_ap_start_reg;

assign state_addr_25_reg_708 = 64'd1;

assign state_addr_26_reg_713 = 64'd2;

assign state_addr_48_reg_954 = 64'd24;

assign state_addr_reg_698 = 64'd0;

assign state_address0 = state_address0_local;

assign state_address1 = state_address1_local;

assign state_ce0 = state_ce0_local;

assign state_ce1 = state_ce1_local;

assign state_d0 = state_d0_local;

assign state_d1 = state_d1_local;

assign state_we0 = state_we0_local;

assign state_we1 = state_we1_local;

endmodule //sha3_256_hw_KeccakF1600_StatePermute
